Feature/tabs hashes
REBELinBLUE/deployer-frontend pull request #2
Opened 2018-08-06 12:55 UTC by axeloz

Source files for https://github.com/REBELinBLUE/deployer/pull/390

2018-09-04 22:06 UTC, REBELinBLUE requested changes

2018-09-04 22:06 UTC, REBELinBLUE commented on webpack.mix.js
> +const build = '../deployer/public';
please can you revert this line

2018-09-05 09:25 UTC, axeloz commented on webpack.mix.js
> +const build = '../deployer/public';
Ooops sorry, my bad. That allows me to build directly into the deployer document root using `yr run watch-poll`. Fixed

2018-09-16 16:42 UTC, REBELinBLUE commented
Can you rebase with master

2018-09-17 08:53 UTC, axeloz commented
I did a rebase after a sync between my fork and your repo. I hope I did it well...

2022-11-02 15:35 UTC, closed without merging